name: build n release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: build
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: make release
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-pc-windows-msvc/release/buhttery.exe
          body: |
            buhttery ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
